#!/bin/bash
# Generate tmux theme configuration file

generate_tmux_theme() {
    local theme_file="$1"
    local output_file="$2"

    # Read tmux colors from theme
    local status_bg=$(read_toml "$theme_file" "apps.tmux" "status_bg")
    local status_fg=$(read_toml "$theme_file" "apps.tmux" "status_fg")
    local border=$(read_toml "$theme_file" "apps.tmux" "border")
    local border_active=$(read_toml "$theme_file" "apps.tmux" "border_active")
    local message_bg=$(read_toml "$theme_file" "apps.tmux" "message_bg")
    local message_fg=$(read_toml "$theme_file" "apps.tmux" "message_fg")
    local session_bg=$(read_toml "$theme_file" "apps.tmux" "session_bg")
    local session_fg=$(read_toml "$theme_file" "apps.tmux" "session_fg")
    local window_fg=$(read_toml "$theme_file" "apps.tmux" "window_fg")
    local window_active_fg=$(read_toml "$theme_file" "apps.tmux" "window_active_fg")
    local clock_fg=$(read_toml "$theme_file" "apps.tmux" "clock_fg")

    # Create parent directory if needed
    mkdir -p "$(dirname "$output_file")"

    cat > "$output_file" << EOF
# Auto-generated by set-theme - DO NOT EDIT

# Status bar
set -g status-style "bg=#$status_bg,fg=#$status_fg"

# Pane borders
set -g pane-border-style "fg=#$border"
set -g pane-active-border-style "fg=#$border_active"

# Message style
set -g message-style "bg=#$message_bg,fg=#$message_fg"

# Status left (session name)
set -g status-left "#[bg=#$session_bg,fg=#$session_fg,bold] #S #[bg=#$status_bg] "

# Status right (time/date)
set -g status-right "#[fg=#$window_fg]%H:%M #[fg=#$clock_fg]%d-%m-%Y "

# Window status
setw -g window-status-format "#[fg=#$window_fg] #I:#W "
setw -g window-status-current-format "#[fg=#$window_active_fg,bold] #I:#W "
EOF

    # Reload tmux config if tmux is running
    if command -v tmux &> /dev/null && [ -n "$TMUX" ]; then
        tmux source-file ~/.config/tmux/tmux.conf 2>/dev/null || true
    fi
}
